// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod a6 {
  use super::*;
  pub mod err {
    use super::*;
    mod code_generated;
    pub use self::code_generated::*;
    mod resp_generated;
    pub use self::resp_generated::*;
  } // err
  pub mod extra_info {
    use super::*;
    mod info_generated;
    pub use self::info_generated::*;
    mod var_generated;
    pub use self::var_generated::*;
    mod req_body_generated;
    pub use self::req_body_generated::*;
    mod resp_body_generated;
    pub use self::resp_body_generated::*;
    mod req_generated;
    pub use self::req_generated::*;
    mod resp_generated;
    pub use self::resp_generated::*;
  } // extra_info
  pub mod httpreq_call {
    use super::*;
    mod action_generated;
    pub use self::action_generated::*;
    mod req_generated;
    pub use self::req_generated::*;
    mod stop_generated;
    pub use self::stop_generated::*;
    mod rewrite_generated;
    pub use self::rewrite_generated::*;
    mod resp_generated;
    pub use self::resp_generated::*;
  } // httpreq_call
  pub mod httpresp_call {
    use super::*;
    mod req_generated;
    pub use self::req_generated::*;
    mod resp_generated;
    pub use self::resp_generated::*;
  } // httpresp_call
  pub mod prepare_conf {
    use super::*;
    mod req_generated;
    pub use self::req_generated::*;
    mod resp_generated;
    pub use self::resp_generated::*;
  } // prepare_conf
  mod method_generated;
  pub use self::method_generated::*;
  mod text_entry_generated;
  pub use self::text_entry_generated::*;
  mod data_entry_generated;
  pub use self::data_entry_generated::*;
} // a6
