// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum RespOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Resp<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Resp<'a> {
  type Inner = Resp<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> Resp<'a> {
  pub const VT_CODE: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Resp { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RespArgs
  ) -> flatbuffers::WIPOffset<Resp<'bldr>> {
    let mut builder = RespBuilder::new(_fbb);
    builder.add_code(args.code);
    builder.finish()
  }


  #[inline]
  pub fn code(&self) -> Code {
    self._tab.get::<Code>(Resp::VT_CODE, Some(Code::BAD_REQUEST)).unwrap()
  }
}

impl flatbuffers::Verifiable for Resp<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<Code>("code", Self::VT_CODE, false)?
     .finish();
    Ok(())
  }
}
pub struct RespArgs {
    pub code: Code,
}
impl<'a> Default for RespArgs {
  #[inline]
  fn default() -> Self {
    RespArgs {
      code: Code::BAD_REQUEST,
    }
  }
}

pub struct RespBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RespBuilder<'a, 'b> {
  #[inline]
  pub fn add_code(&mut self, code: Code) {
    self.fbb_.push_slot::<Code>(Resp::VT_CODE, code, Code::BAD_REQUEST);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RespBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RespBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Resp<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Resp<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Resp");
      ds.field("code", &self.code());
      ds.finish()
  }
}
